#!/bin/sh

# ルートのlint-stagedを実行
npx lint-staged

# clientアプリのlint-stagedを実行
cd apps/client
if [ -f "package.json" ]; then
  echo "Running client lint-staged..."
  npx lint-staged
fi
cd ../..

# serverアプリのlint-stagedを実行
cd apps/server
if [ -f "package.json" ]; then
  echo "Running server lint-staged..."
  npx lint-staged
fi
cd ../..
